### PR TITLE
Make services public so they can be obtained from the container in Symfony 4 and beyond

### PR DESCRIPTION
**Pull request by enekochan**
Some services still weren't declared as public.

### CODE REVIEW

**Comment by geekdevs** [comment]
@enekochan Thanks, please check issue with tests

**Comment by enekochan** [comment]
Looks like the problem is that this URL does not work any more:

https://finance.google.com/finance/converter?a=%s&from=%s&to=%s

In TbbcMoneyBundle/Pair/RatioProvider/GoogleRatioProvider.php line 56.

It's been moved to https://finance.google.com/bctzjpnsun/converter

Ref: https://www.j2store.org/blog/j2store/google-finance-api-url-has-been-updated.html

**Comment by enekochan** [comment]
@geekdevs Isn't it odd that no one noticed the error in the endpoint before? I personally don't use the ratio converter so this doesn't affect me at the moment.

**Comment by geekdevs** [comment]
@enekochan I guess that's because master is still alpha and not really used much. It was already fixed on 3.x branch (which is latest stable release).

**Comment by enekochan** [comment]
It is fixed on 3.x branch but not in [latests stable tag 3.1.4](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/v3.1.4/Pair/RatioProvider/GoogleRatioProvider.php#L55) which is installed with composer if you don't specify another branch/tag.

**Comment by enekochan** [comment]
Well, actually the link on 3.x branch is wrong:

https://finance.google.com/bctzjpnsun/converter?a=1&from=%s&from=%s&to=%s

Should be:

https://finance.google.com/bctzjpnsun/converter?a=%s&from=%s&to=%s

**Comment by geekdevs** [comment]
@enekochan hmm, you're right. Would you make another PR to fix that on 3.x please?

**Pull request merged**
