### PR TITLE
Symfony4 support bis

### PR DESCRIPTION
**Pull request by allan-simon**
based on job done here https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/84 

+ some additional corrections
+ check for php7.2 that is now stable

### CODE REVIEW

**Comment by allan-simon** [comment]
test are failing, i'm checking that.

**Comment by allan-simon** [comment]
a bit more of deprecated stuff to fix, I will look into that tomorrow.

**Comment by allan-simon** [comment]
tests are passing now :) all is good

**Comment by allan-simon** [comment]
up?

**Comment by geekdevs** [comment]
Checking this quickly - seems to be good, but what do these opening private services a public have to do with symfony4?

**Comment by allan-simon** [comment]
hmmm if I remember if was due to the way they are used in the test

**Comment by geekdevs** [comment]
but no tests seem to be changed

**Comment by allan-simon** [comment]
it's because before the "public/private" being not specific , it was considered as public by default, and now it's private by default , hence why the test hasn't changed but the service declaration changed.

**Comment by geekdevs** [comment]
@allan-simon clear, thanks - merged

**Comment by allan-simon** [comment]
thanks

**Pull request merged**
