### PR TITLE
Add ability to define custom doctrine type class

### PR DESCRIPTION
**Pull request by akovalyov**
Usecase: right now, I'd like to test the bundle, but I don't have a need to have multi-currency support, so I don't see a reason to keep currency code in db.
I am not sure if the configuration key is the best name ever, so we might change that.

What do you think?

### CODE REVIEW

**Comment by geekdevs** [comment]
@akovalyov my plan for next major version was to remove automatic type registration and advice user to do so manually when needed. See discussion here https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/issues/38#issuecomment-256012838

**Comment by akovalyov** [comment]
thank you, it totally makes sense.

**Comment by akovalyov** [comment]
@geekdevs BTW, I think, we can add deprecation warning before https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/master/DependencyInjection/Compiler/DoctrineTypeCompilerPass.php#L29 and edit installation section with instructions about manual type registration. I can do that if you want, in next couple of days.

**Comment by geekdevs** [comment]
@akovalyov I think deprecation message is probably not necessary since we release major version. Lots of things will break anyway (take moneyphp v.3 alone). 
I would rather prepare change log explaining what was changed and how to migrate to new major version (I started preparing it here https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/feature_money_3/change-log-4.0.md).

Here I think it should be simple - just need to remove Doctrine Type compile path and add readme, changelog.
Any help is very much appreciated.

**Comment by geekdevs** [comment]
@akovalyov Did you have a chance to look into that yet?

**Comment by akovalyov** [comment]
@geekdevs I apologize for delay, there is always less free time than you want. 
PR https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/74 is ready for review ;)

**Pull request closed without merging**
