### PR TITLE
Remove deprecated ObjectManager for Symfony5 and replace with EntityManagerInterface

### PR DESCRIPTION
**Pull request by mogilvie**
Resolves issue #128

### CODE REVIEW

**Comment by wouter-toppy** [comment]
any update on this?

**Comment by wouter-toppy** [comment]
can someone please merge this one?

**Comment by Perf** [comment]
Thank you @mogilvie for this PR!
@geekdevs could you please merge it?

**Comment by grekpg** [comment]
any update ?

**Comment by grekpg** [comment]
@philippe-levan  @geekdevs @armetiz @hugues-m TheBigBrainsCompany please to accept this merge

**Comment by philippe-levan** [comment]
Sorry for this very late merge.

I don't have a lot of time to maintain this bundle anymore. does anyone want to be added as a maintainer of this bundle ? 

@mogilvie ?

Best regards,
Philippe

**Comment by grekpg** [comment]
@philippe-levan  You can add my and @mogilvie

**Comment by philippe-levan** [comment]
Hi,

I created a tag 4.1.0 for your fix and two others PR.

I added you both to the maintainers of this package. Welcome to the team ! :champagne: 

Best regards, Philippe

**Pull request merged**
