### PR TITLE
Ability to use bundle services independently of reference currency

### PR DESCRIPTION
**Pull request by sovaalexandr**
All changes are backwards-compatible. Checked by existent tests

### CODE REVIEW

**Comment by verschoof** [comment]
@sovaalexandr what about this PR? Should this be merged? since its has conflicts.
I also see that you add documentation in this pr that this is a "fork"? I think that shouldn't be in this PR?

**Comment by sovaalexandr** [comment]
It shouldn't be merged with current state and this code is so old that I don't actually remember what is it for.
Maybe I'll find couple of hours to fix it within a month or to close it if it's not needed.

**Comment by geekdevs** [comment]
@sovaalexandr are you going to finish this?

**Comment by geekdevs** [comment]
@sovaalexandr I like where you go with your updates, but it needs finishing - would you please check?

In general, my advise when creating PR - add small portions of code which are directly related to the subject. Fixing code style and making other improvements along the way is nice, but makes it much harder to review the actual feature and solve conflicts afterwards - better placing them in separate PRs.

**Comment by geekdevs** [comment]
Closing because of no response. I find it quite complicated to merge/solve issues in current code state especially now as we're restructuring for money v.3. 
But we might use some of the ideas from this PR to re-implement this in future.

**Comment by sovaalexandr** [comment]
Yes, sure. Thank you for closing. I should been asked for it much earlier. Just forgot to do it.

**Pull request closed without merging**
