### PR TITLE
feat: improve ratio list command (add option "format")

### PR DESCRIPTION
**Pull request by Chris53897**
Like some symfony commands `./bin/console lint:twig --format=json`

The default is `txt` to not introduce BC breaks.

### CODE REVIEW

**Comment by johanwilfer** [comment]
Looks great! Will you address the new psalm errors at least @Chris53897 ?

**Comment by Chris53897** [comment]
Yes, i will do this. Will do it in my next free timeslot.

**Comment by Chris53897** [comment]
I have fixed the two direct related psalm errors, and added tests for the new formats.

**Comment by johanwilfer** [comment]
Awesome! Thanks for this! Will merge it :)

**Pull request merged**
