### PR TITLE
feat: remove support for "moneyphp/money" < 4.5

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/issues/171

I need to take a deeper look, if there are tests or bc layers that can be removed.
https://github.com/moneyphp/money/blob/master/CHANGELOG.md#400---2021-05-17

### CODE REVIEW

**Comment by johanwilfer** [comment]
Looks good, you plan to take a look in the scope of this PR?

**Comment by Chris53897** [comment]
I can do. Will try next weekend.

**Comment by Chris53897** [comment]
I did check the changelog, and i think there is no other change needed.
I found no use of BC breaks in this repo.

**Comment by johanwilfer** [comment]
Great!

**Pull request merged**
