### PR TITLE
feat: remove symfony/templating

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/issues/152

### CODE REVIEW

**Comment by johanwilfer** [comment]
Can I ask for your help here @Chris53897 ? Seems we have this code in the extension:
```
        if (in_array('twig', $config['templating']['engines'], true)) {
            $loader->load('twig_extension.xml');
        }
```

This now fails when I removed the configuration for templating. Not sure if we should load that unconditionally now?

**Comment by johanwilfer** [comment]
I have tagged a new 5.2 version and made a 5.x branch where we can commit fixes for the 5.x 
And once this is ready we can merge it to master to release 6.x from master when we are ready for that.

**Comment by Chris53897** [comment]
<< Not sure if we should load that unconditionally now?
I did ask myself the same question. But i think you should decide this as the maintainer ;)
Maybe it is easier to maintain if we just load it unconditionally.

**Comment by johanwilfer** [comment]
> I did ask myself the same question. But i think you should decide this as the maintainer ;)
> Maybe it is easier to maintain if we just load it unconditionally.

Well, I ended up as the maintainer after submitting a few patches ;) 
So if you want to aid here I am really interested in what you think.

Lets load it unconditionally then, in all the projects I use it I have twig anyway and can't see how that could harm.

**Comment by johanwilfer** [comment]
Now this looks good I think, what do you say @Chris53897 - merge this to master (to be 6.x) ?

**Comment by Chris53897** [comment]
Sounds good to me. After that the 2 other PRs can be merged, and after that two seperate PR to fix some psalm erros, and add re-introduce support for doctrine/orm 3

**Comment by johanwilfer** [comment]
> Sounds good to me. After that the 2 other PRs can be merged, and after that two seperate PR to fix some psalm erros, and add re-introduce support for doctrine/orm 3

Sounds great, I will merge this then!

**Comment by Chris53897** [comment]
Of course please wait with tags for 6.x until this is all stable and tested,

**Pull request merged**
