### PR TITLE
Fix `tbbc_money.pair_history_manager` service definition

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Comment by johanwilfer** [comment]
@hhamon Was this broken by the last PR (to make it optional with Doctorine if you use only MongoDB) or what is the background for this PR?

**Comment by hhamon** [comment]
@johanwilfer after upgrading from `6.0.0` to `6.0.1`, my CI fails:

```
> @php bin/console lint:container


 [ERROR] Invalid definition for service "tbbc_money.pair_history_manager":
         "Tbbc\MoneyBundle\PairHistory\PairHistoryManager::__construct()" requires 2 arguments, 1 passed.

```

**Comment by johanwilfer** [comment]
Yeah, this basically reverts https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/180

@mustanggb What do you suggest? Any way to make it optional for MongoDb users still or do we have to revert your change?

**Comment by mustanggb** [comment]
I don't know how to denote that a service is optional, perhaps someone cleverer than me does.

However as this was a new addition anyway, we can just remove it, as per #182.

**Comment by hhamon** [comment]
I think it must be resolved with a DI compiler pass

**Review by johanwilfer — APPROVED** [review]

**Comment by johanwilfer** [comment]
For now I will merge this, to revert this until we resolved it properly.

**Pull request merged**
