### PR TITLE
Make amount and currency type configurable.

### PR DESCRIPTION
**Pull request by tautelis**
Example case:
```
...
->add(
    'price',
    SimpleMoneyType::class,
    [
        'tbbc_amount_options' => ['label' => false],
    ]
)
...
```

### CODE REVIEW

**Comment by mvar** [comment]
Any plans to merge this PR? :)

CC @geekdevs

**Comment by tautelis** [comment]
maybe TheBigBrainsCompany went bankrupt or something...

**Comment by tautelis** [comment]
okay, nevermind... we are not using your bundle anymore

**Comment by geekdevs** [comment]
The reason I did not merge is because I don't think this is correct approach to do things. 
This component is one entity - if you want to adjust design you should do this on twig level and not configure its separate parts.

**Pull request closed without merging**
